{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.zekerzhayard",
    "module": "ForgeWrapper",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeWrapper-1.5.1.jar",
          "url": "ForgeWrapper-1.5.1.jar",
          "size": 29892,
          "sha512": "a64e471f5f7487cace9cf7d531a554edc1977b9e5f4fc28ddcfa7a8ec4e2de9af0f5fd9aa8466eab596222f5fd3b6c43e029234498132f61eabbb386877b9f34",
          "sha256": "d608aad3a92d69c1c9f93c019d671b7242a4383451edeb728bb2482d2b900164",
          "sha1": "90104e9aaa8fbedf6c3d1f6d0b90cabce080b5a9",
          "md5": "919e2d600b673fce7be6ac2d0ed1b62f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ForgeWrapper-1.5.1.jar",
          "url": "ForgeWrapper-1.5.1.jar",
          "size": 29892,
          "sha512": "a64e471f5f7487cace9cf7d531a554edc1977b9e5f4fc28ddcfa7a8ec4e2de9af0f5fd9aa8466eab596222f5fd3b6c43e029234498132f61eabbb386877b9f34",
          "sha256": "d608aad3a92d69c1c9f93c019d671b7242a4383451edeb728bb2482d2b900164",
          "sha1": "90104e9aaa8fbedf6c3d1f6d0b90cabce080b5a9",
          "md5": "919e2d600b673fce7be6ac2d0ed1b62f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ForgeWrapper-1.5.1-sources.jar",
          "url": "ForgeWrapper-1.5.1-sources.jar",
          "size": 11159,
          "sha512": "fac731ea67b9d44822afbc3d21346be4efef68e6445124195566674d48c180c7e1143bffe9b985a890f8631173356d1bac2e72b94d30f0fe89242a312abfe60f",
          "sha256": "6d8efdbda45653934d0a28797987c8783710026f7c42b3ea5e2c3f7117a7af70",
          "sha1": "5ecf7d1102a4a0e82ad82b4a5499130c0bf7102b",
          "md5": "41889b31cb86400ad7053037e006407a"
        }
      ]
    }
  ]
}
