name: Publication

on:
  push:
    tags:
      - "mmc*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Determine version based on the tag
      - id: version
        name: Write release version
        run: |
          echo Version: $GITHUB_REF_NAME
          echo "version=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "8.0.312"
          architecture: x64
      - name: Build with Gradle
        env:
          IS_PUBLICATION: true
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          chmod +x ./gradlew
          ./gradlew publish -iS -Pversion=${VERSION}
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/libs
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: ${{ steps.version.outputs.version }}
          body: ""
          draft: false
          prerelease: false
      - name: Upload release binaries
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./build/libs/*"]'
